name: dataviewer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: node index.js
        run: |
          cd RestAPI
          node index.js

      - name: cd data
        run: |
          cd dataviewer/resource/
          ls
